serverAddr = "dw.edge.home.geekcity.tech"
serverPort = 32700
loginFailExit = false

auth.method = "token"
auth.tokenSource.type = "file"
auth.tokenSource.file.path = "/run/secrets/frp-auth"

transport.tls.enable = true

log.to = "console"
log.level = "info"
log.disablePrintColor = true

[[proxies]]
name = "cloud01-ssh"
type = "tcp"
localIP = "127.0.0.1"
localPort = 22
remotePort = 6000
transport.useEncryption = true

healthCheck.type = "tcp"
healthCheck.timeoutSeconds = 3
healthCheck.maxFailed = 3
healthCheck.intervalSeconds = 10
