kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: aria2-downloads-pvc
spec:
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: "local-path"
