ARG SSHPIPER_IMAGE=ghcr.io/tg123/sshpiperd:full-v1.5.3
ARG GO_IMAGE=golang:1.25-bookworm

FROM ${GO_IMAGE} AS builder

WORKDIR /src
COPY src/go.mod ./go.mod
COPY src/go.sum ./go.sum
COPY src/*.go ./
RUN go mod download && CGO_ENABLED=0 GOOS=linux GOARCH=$(go env GOARCH) go build -o /out/routeauth .

FROM ${SSHPIPER_IMAGE}

COPY --from=builder /out/routeauth /sshpiperd/plugins/routeauth
