apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "aria2.fullname" . }}
  labels:
    {{- include "aria2.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: {{ .Values.ingress.path }}
        pathType: {{ .Values.ingress.pathType }}
        backend:
          service:
            name: {{ include "aria2.fullname" . }}
            port:
              number: {{ .Values.service.ports.ariaNg }}