{{- if and .Values.server.enabled .Values.server.ingress.enabled .Values.server.ingress.auth.enabled (not .Values.server.ingress.auth.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chromium-bridge.ingressCredentials.secretName" (dict "context" . "component" "server" "ingress" .Values.server.ingress) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.server.ingress.auth.username | quote }}
  password: {{ include "chromium-bridge.ingressCredentials.password" (dict "context" . "component" "server" "ingress" .Values.server.ingress) | quote }}
  auth: {{ htpasswd .Values.server.ingress.auth.username (include "chromium-bridge.ingressCredentials.password" (dict "context" . "component" "server" "ingress" .Values.server.ingress)) | quote }}
  users: {{ htpasswd .Values.server.ingress.auth.username (include "chromium-bridge.ingressCredentials.password" (dict "context" . "component" "server" "ingress" .Values.server.ingress)) | quote }}
---
{{- end -}}
{{- if and .Values.novnc.enabled .Values.novnc.ingress.enabled .Values.novnc.ingress.auth.enabled (not .Values.novnc.ingress.auth.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chromium-bridge.ingressCredentials.secretName" (dict "context" . "component" "novnc" "ingress" .Values.novnc.ingress) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.novnc.ingress.auth.username | quote }}
  password: {{ include "chromium-bridge.ingressCredentials.password" (dict "context" . "component" "novnc" "ingress" .Values.novnc.ingress) | quote }}
  auth: {{ htpasswd .Values.novnc.ingress.auth.username (include "chromium-bridge.ingressCredentials.password" (dict "context" . "component" "novnc" "ingress" .Values.novnc.ingress)) | quote }}
  users: {{ htpasswd .Values.novnc.ingress.auth.username (include "chromium-bridge.ingressCredentials.password" (dict "context" . "component" "novnc" "ingress" .Values.novnc.ingress)) | quote }}
{{- end -}}
