{{- if and .Values.openvscode.enabled (not .Values.openvscode.connection.token.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "podman-in-container.openvscodSecret.name" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  connection-token: {{ include "podman-in-container.openvscodSecret.token" . | quote }}
{{- end }}
