import type { ActivityItem, Project, Session, Task } from './types'

export const projects: Project[] = [
	{
		id: 'PRJ-001',
		name: 'Agent Task Manager',
		slug: 'agent-task-manager',
		open: 24,
		inProgress: 7,
		inReview: 3,
		updatedAt: '2 min ago',
		summary: 'Go-based rebuild focused on agent-first task orchestration, explicit auditability, and durable session snapshots.',
	},
	{
		id: 'PRJ-002',
		name: 'OpenClaw Worker Orchestration',
		slug: 'openclaw-worker-orchestration',
		open: 11,
		inProgress: 4,
		inReview: 2,
		updatedAt: '17 min ago',
		summary: 'Dynamic OpenCode worker lifecycle, role packaging, and orchestration flow design.',
	},
	{
		id: 'PRJ-003',
		name: 'Pith Migration Research',
		slug: 'pith-migration-research',
		open: 7,
		inProgress: 1,
		inReview: 1,
		updatedAt: '46 min ago',
		summary: 'Feature mapping, migration gaps, and task-model constraints from the previous system.',
	},
]

export const tasks: Task[] = [
	{
		id: 'ATM-101',
		title: 'Rebuild task domain in Go',
		project: 'agent-task-manager',
		projectName: 'Agent Task Manager',
		status: 'in_progress',
		priority: 'P0',
		assignee: 'builder-agent',
		labels: ['backend', 'domain'],
		summary: 'Replace the old TypeScript task model with Go-first services and persistence boundaries.',
		updatedAt: '12 min ago',
		parent: 'ATM-099 Build agent-task-manager backend MVP',
		subtasks: ['ATM-121 Define task repositories', 'ATM-122 Add task activity events'],
		acceptance: [
			'Task CRUD endpoints mapped to Go service boundaries.',
			'Repository interfaces do not leak HTTP concerns.',
			'Status transitions create audit log entries.',
		],
	},
	{
		id: 'ATM-102',
		title: 'Design agent-first CLI contracts',
		project: 'agent-task-manager',
		projectName: 'Agent Task Manager',
		status: 'todo',
		priority: 'P0',
		assignee: 'product-agent',
		labels: ['cli', 'agent'],
		summary: 'Define deterministic command outputs, JSON mode, and task/session workflows for automation.',
		updatedAt: '29 min ago',
	},
	{
		id: 'ATM-103',
		title: 'Refactor frontend shell around Tasks workspace',
		project: 'agent-task-manager',
		projectName: 'Agent Task Manager',
		status: 'in_review',
		priority: 'P1',
		assignee: 'ui-agent',
		labels: ['frontend', 'ux'],
		summary: 'Replace top-level demo tabs with a sidebar shell, top utility bar, and contextual preview panel.',
		updatedAt: '5 min ago',
	},
	{
		id: 'ATM-104',
		title: 'Add task reparenting support',
		project: 'agent-task-manager',
		projectName: 'Agent Task Manager',
		status: 'backlog',
		priority: 'P1',
		assignee: 'unassigned',
		labels: ['api', 'tasks'],
		summary: 'Support parent changes after task creation and surface them explicitly in the audit timeline.',
		updatedAt: '41 min ago',
	},
	{
		id: 'OCW-205',
		title: 'Launch product-role OpenCode worker',
		project: 'openclaw-worker-orchestration',
		projectName: 'OpenClaw Worker Orchestration',
		status: 'in_progress',
		priority: 'P0',
		assignee: 'product-role-worker',
		labels: ['openclaw', 'opencode'],
		summary: 'Provision a product-role worker with imported product and UI design skills.',
		updatedAt: '58 min ago',
	},
	{
		id: 'PMR-031',
		title: 'Capture parent-linking gap from pith',
		project: 'pith-migration-research',
		projectName: 'Pith Migration Research',
		status: 'todo',
		priority: 'P2',
		assignee: 'research-agent',
		labels: ['pith', 'task-model', 'ux'],
		summary: 'Record the limitation that parent linkage cannot be added after task creation.',
		updatedAt: '1 hr ago',
	},
]

export const sessions: Session[] = [
	{
		title: 'OpenCode backend domain pass 1',
		snapshotId: 'b4f84a13-7d8e-4fd6-9a13-e9a7f94b3901',
		description: 'Snapshot imported after backend domain refactor checkpoint.',
		artifactName: 'ses_1bc5ca7a9ffeI2yl8CnNXcBxVk.json',
		artifactPath: 's3://agent-task-manager/sessions/opencode/ses_1bc5ca7a9ffeI2yl8CnNXcBxVk.json',
		updatedAt: '9 min ago',
	},
	{
		title: 'OpenCode board UX review snapshot',
		snapshotId: '0b72c993-0ae4-4d96-a21e-7e0ef6265830',
		description: 'Snapshot saved while evaluating board density and task card layout.',
		artifactName: 'ses_ux_board_review.json',
		artifactPath: '/data/snapshots/opencode/ses_ux_board_review.json',
		updatedAt: '37 min ago',
	},
	{
		title: 'OpenCode CLI contract draft snapshot',
		snapshotId: 'd8f720ce-1d1b-4556-b7bb-c2a52c9a65cb',
		description: 'Snapshot captured before revising agent CLI command contracts.',
		artifactName: 'ses_cli_contract_draft.json',
		artifactPath: 's3://agent-task-manager/sessions/opencode/ses_cli_contract_draft.json',
		updatedAt: '1 hr ago',
	},
]

export const activities: ActivityItem[] = [
	{
		id: 'ACT-006',
		title: 'builder-agent started backend domain pass',
		detail: 'Task ATM-101 is being restructured around repositories, services, and activity events.',
		updatedAt: '2 min ago',
		sortKey: 6,
		project: 'agent-task-manager',
		projectName: 'Agent Task Manager',
		task: 'ATM-101',
		labels: ['backend', 'domain'],
	},
	{
		id: 'ACT-005',
		title: 'ui-agent moved ATM-103 to in_review',
		detail: 'The new shell, Tasks workspace, and preview panel are ready for product review.',
		updatedAt: '14 min ago',
		sortKey: 5,
		project: 'agent-task-manager',
		projectName: 'Agent Task Manager',
		task: 'ATM-103',
		labels: ['frontend', 'ux'],
	},
	{
		id: 'ACT-004',
		title: 'product-agent created ATM-104',
		detail: 'Task reparenting is now treated as a first-class requirement in the rebuilt system.',
		updatedAt: '27 min ago',
		sortKey: 4,
		project: 'agent-task-manager',
		projectName: 'Agent Task Manager',
		task: 'ATM-104',
		labels: ['api', 'tasks'],
	},
	{
		id: 'ACT-003',
		title: 'admin commented on ATM-101',
		detail: 'Parent changes should be explicit and audit-friendly in both API output and task detail.',
		updatedAt: '43 min ago',
		sortKey: 3,
		project: 'agent-task-manager',
		projectName: 'Agent Task Manager',
		task: 'ATM-101',
		labels: ['backend', 'tasks'],
	},
	{
		id: 'ACT-002',
		title: 'product-role worker task linked to initiative',
		detail: 'The product-role worker flow now lives as a proper subtask under the orchestration initiative.',
		updatedAt: '58 min ago',
		sortKey: 2,
		project: 'openclaw-worker-orchestration',
		projectName: 'OpenClaw Worker Orchestration',
		task: 'OCW-205',
		labels: ['openclaw', 'opencode', 'orchestration'],
	},
	{
		id: 'ACT-001',
		title: 'migration analysis captured parent-linking gap',
		detail: 'A task model limitation was recorded after finding that parent linkage could not be added after task creation.',
		updatedAt: '1 hr ago',
		sortKey: 1,
		project: 'pith-migration-research',
		projectName: 'Pith Migration Research',
		task: 'PMR-031',
		labels: ['pith', 'task-model', 'ux'],
	},
]
