#!/bin/bash

set -o errexit -o nounset -o pipefail

# SSH setup
ENABLE_SSH=${ENABLE_SSH:-"true"}
if [[ "${ENABLE_SSH}" == "true" ]]; then
  mkdir -p $HOME/.ssh
  chmod 700 $HOME $HOME/.ssh
  if [[ ! -f /etc/ssh/ssh_host_rsa_key ]]; then
    echo "Generating SSH host keys..."
    ssh-keygen -A
  fi
  if [[ -n "${AUTHORIZED_KEYS:-}" ]]; then
    echo "${AUTHORIZED_KEYS}" > $HOME/.ssh/authorized_keys
    chmod 600 $HOME/.ssh/authorized_keys
    echo "SSH authorized keys have been configured by env: AUTHORIZED_KEYS"
  fi
  /usr/sbin/sshd -D -E /var/log/sshd.log &
fi

# Claude Code setup
# Check if both required environment variables are set
if [[ -n "${ANTHROPIC_BASE_URL:-}" ]] && [[ -n "${ANTHROPIC_AUTH_TOKEN:-}" ]]; then
  echo "Claude Code is enabled (ANTHROPIC_BASE_URL and ANTHROPIC_AUTH_TOKEN are set)"

  # Export Claude Code environment variables for SSH sessions
  echo "Exporting Claude Code environment variables to /etc/profile.d/claude-code-env.sh..."
  {
    echo "# Claude Code environment variables - auto-generated by entrypoint"
    echo "export ANTHROPIC_BASE_URL='${ANTHROPIC_BASE_URL}'"
    echo "export ANTHROPIC_AUTH_TOKEN='${ANTHROPIC_AUTH_TOKEN}'"
  } > /etc/profile.d/claude-code-env.sh
  chmod 644 /etc/profile.d/claude-code-env.sh

  # Test Claude Code installation
  if command -v claude &> /dev/null; then
    echo "Testing Claude Code installation..."
    claude -v
    echo "Claude Code is ready to use"
  else
    echo "Warning: Claude Code command not found, but environment variables are set"
  fi
else
  echo "Claude Code is disabled (ANTHROPIC_BASE_URL or ANTHROPIC_AUTH_TOKEN not set)"
fi

wait
