server:
  image:
    repository: 127.0.0.1:31666/chromium-bridge-server
    tag: 0.1.0
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    cdpPort: 9222
    vncPort: 5900
    nodePorts:
      cdp: 30222
      vnc: 30900

novnc:
  image:
    repository: 127.0.0.1:31666/chromium-bridge-novnc
    tag: 0.1.0
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 6080
    nodePort: 30080
