apiVersion: v2
name: aria2
version: 1.0.0
appVersion: "latest"
description: aria2 downloader with AriaNg web UI
type: application
keywords:
  - aria2
  - downloader
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
home: https://github.com/ben-wangz/k8s-at-home
sources:
- https://github.com/ben-wangz/k8s-at-home/tree/main/application/aria2
maintainers:
  - name: ben
    email: ben.wangz@foxmail.com
