commonLabels: {}
commonAnnotations: {}
podLabels: {}
podAnnotations: {}
revisionHistoryLimit: 10
updateStrategy: {}
imagePullSecrets: []
affinity: {}
podAffinityPreset: ''
podAntiAffinityPreset: soft
nodeAffinityPreset:
  type: none
  key: ''
  values: []
podSecurityContext:
  enabled: true
  fsGroupChangePolicy: Always
  supplementalGroups: []
  fsGroup: 1001
nodeSelector: {}
tolerations: []
extraVolumes: []
aria2:
  image:
    repository: ghcr.io/ben-wangz/k8s-at-home-aria2
    tag: 1.0.0
    pullPolicy: IfNotPresent
  ports:
    rpc: 6800
    p2p: 6868
  timezone: Asia/Shanghai
  rpcSecret: your-rpc-secret
  extraEnvVars: {}
  extraEnvVarsSecret: ''
  extraVolumeMounts: []
  resourcesPreset: medium
  customLivenessProbe: {}
  customReadinessProbe: {}
  customStartupProbe: {}
ariaNg:
  image:
    repository: ghcr.io/ben-wangz/k8s-at-home-aria-ng
    tag: 1.0.0
    pullPolicy: IfNotPresent
  ports:
    http: 8080
  timezone: Asia/Shanghai
  rpcHost: 127.0.0.1
  rpcPort: '6800'
  resourcesPreset: small
  customLivenessProbe: {}
  customReadinessProbe: {}
  customStartupProbe: {}
persistence:
  enabled: true
  storageClass: ''
  existingClaim: ''
  accessModes:
  - ReadWriteOnce
  size: 10Gi
  subPath: ''
  annotations: {}
  selector: {}
  dataSource: {}
service:
  type: ClusterIP
  ports:
    p2p: 6868
    ariaNg: 8080
  annotations: {}
  clusterIP: ''
  sessionAffinity: ''
  sessionAffinityConfig: {}
  externalTrafficPolicy: ''
  loadBalancerSourceRanges: []
  loadBalancerIP: ''
  loadBalancerClass: ''
  extraPorts: []
ingress:
  enabled: true
  annotations: {}
  ingressClassName: nginx
  hostname: aria2.ben.zjlab.geekcity.tech
  path: /
  pathType: Prefix
  tls: false
test:
  service:
    annotations: {}
