{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "agent-task-manager.fullname" . }}-frontend
  labels:
    {{- include "agent-task-manager.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  {{- with .Values.service.web.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.web.type }}
  selector:
    {{- include "agent-task-manager.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: {{ .Values.service.web.port }}
      targetPort: http
{{- end }}
