{{- if and (not .Values.tabminal.existingSecret) (or .Values.tabminal.password .Values.tabminal.openrouterKey .Values.tabminal.openaiKey .Values.tabminal.googleKey .Values.tabminal.googleCx .Values.tabminal.cloudflareKey) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tabminal.secret.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.tabminal.password }}
  password: {{ .Values.tabminal.password | quote }}
  {{- end }}
  {{- if .Values.tabminal.openrouterKey }}
  openrouter-key: {{ .Values.tabminal.openrouterKey | quote }}
  {{- end }}
  {{- if .Values.tabminal.openaiKey }}
  openai-key: {{ .Values.tabminal.openaiKey | quote }}
  {{- end }}
  {{- if .Values.tabminal.googleKey }}
  google-key: {{ .Values.tabminal.googleKey | quote }}
  {{- end }}
  {{- if .Values.tabminal.googleCx }}
  google-cx: {{ .Values.tabminal.googleCx | quote }}
  {{- end }}
  {{- if .Values.tabminal.cloudflareKey }}
  cloudflare-key: {{ .Values.tabminal.cloudflareKey | quote }}
  {{- end }}
{{- end -}}
