apiVersion: v2
name: sshpiper
version: 0.2.5
appVersion: "0.2.5"
description: SSH reverse proxy based on tg123/sshpiper
type: application
keywords:
  - ssh
  - proxy
  - sshpiper
annotations:
  sshpiper/images: |
    - name: sshpiper-proxy
      path: application/sshpiper/container
      valuesKey: image.tag
dependencies:
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.x.x
home: https://github.com/ben-wangz/k8s-at-home
sources:
  - https://github.com/ben-wangz/k8s-at-home/tree/main/application/sshpiper
  - https://github.com/tg123/sshpiper
maintainers:
  - name: ben
