replicas: 1

commonLabels: {}
commonAnnotations: {}
podLabels: {}
podAnnotations: {}

revisionHistoryLimit: 10
updateStrategy: {}

imagePullSecrets: []
affinity: {}
podAffinityPreset: ""
podAntiAffinityPreset: soft
nodeAffinityPreset:
  type: none
  key: ""
  values: []

podSecurityContext:
  enabled: true
  fsGroupChangePolicy: Always
  supplementalGroups: []
  fsGroup: 1001

containerSecurityContext:
  enabled: true
  runAsUser: 1001
  runAsGroup: 1001
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  capabilities:
    drop:
      - ALL

nodeSelector: {}
tolerations: []

image:
  registry: ghcr.io
  repository: ben-wangz/k8s-at-home-sshpiper-proxy
  tag: 0.2.6
  pullPolicy: IfNotPresent

listen:
  address: 0.0.0.0
  port: 22

serverKey:
  existingSecret: ""
  secretName: ""
  secretKey: ssh_host_ed25519_key
  privateKey: ""

service:
  type: NodePort
  ports:
    ssh: 22
    sshNodePort: 32022
  annotations: {}
  clusterIP: ""
  sessionAffinity: ""
  sessionAffinityConfig: {}
  externalTrafficPolicy: ""
  loadBalancerSourceRanges: []
  loadBalancerIP: ""
  loadBalancerClass: ""
  extraPorts: []

storage:
  knownHosts:
    enabled: false
    storageClass: ""
    existingClaim: ""
    accessModes:
      - ReadWriteOnce
    size: 1Gi
    annotations: {}
    selector: {}
    dataSource: {}

auth:
  mode: key
  hostKeyPolicy: tofu
  allowedTargets:
    - gitea-ssh.basic-components
    - "*.codespace"
  authorizedKeys:
    values:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGreplace-this-authorized-key-example sshpiper-user
    existingSecret: ""
    secretName: ""
    secretKey: authorized_keys
    mountPath: /auth
    filePath: /auth/authorized_keys
  upstreamKeypair:
    existingSecret: sshpiper-upstream-keypair
    secretName: ""
    mountPath: /upstream-keypair
    privateKeyPath: /upstream-keypair/id_ed25519
    privateKeyKey: id_ed25519

resources: {}
resourcesPreset: nano

customLivenessProbe: {}
customReadinessProbe: {}
customStartupProbe: {}

extraEnvVars: []
extraEnvVarsSecret: ""
extraVolumeMounts: []
extraVolumes: []

extraDeploy: []
