{{- if not .Values.sub2api.auth.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sub2api.auth.secretName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
type: Opaque
stringData:
  {{ include "sub2api.auth.adminPasswordKey" . }}: {{ include "common.tplvalues.render" (dict "value" .Values.sub2api.auth.adminPassword "context" $) | quote }}
  {{ include "sub2api.auth.jwtSecretKey" . }}: {{ include "common.tplvalues.render" (dict "value" .Values.sub2api.auth.jwtSecret "context" $) | quote }}
  {{ include "sub2api.auth.totpEncryptionKey" . }}: {{ include "common.tplvalues.render" (dict "value" .Values.sub2api.auth.totpEncryptionKey "context" $) | quote }}
{{- end -}}
