apiVersion: v2
name: yacd
version: 0.2.0
description: A Helm chart for yacd (Yet Another Clash Dashboard)
keywords:
  - clash
  - dashboard
maintainers:
  - name: ben.wangz
    email: ben.wangz@foxmail.com
appVersion: "master"
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
