# .github/workflows/publish-images.yaml
name: publish-images
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Optional tag to use for the images (e.g. latest)"
        required: false
        type: string
        default: "latest"
      push:
        description: "Push the images to the registry"
        required: false
        type: boolean
        default: false
  push:
    branches:
      - "main"
    tags:
      - "v*"
env:
  REGISTRY: ghcr.io
jobs:
  build-and-push-images:
    strategy:
      matrix:
        include:
          - name_suffix: "aria-ng"
            container_path: "application/aria2/container/aria-ng"
            dockerfile_path: "application/aria2/container/aria-ng/Dockerfile"
          - name_suffix: "aria2"
            container_path: "application/aria2/container/aria2"
            dockerfile_path: "application/aria2/container/aria2/Dockerfile"
          - name_suffix: "podman-in-container"
            container_path: "application/podman-in-container/container"
            dockerfile_path: "application/podman-in-container/container/Dockerfile"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: checkout-repository
      uses: actions/checkout@v4
    - name: log in to the container registry
      uses: docker/login-action@v3
      with:
        registry: "${{ env.REGISTRY }}"
        username: "${{ github.actor }}"
        password: "${{ secrets.GITHUB_TOKEN }}"
    - name: "extract metadata (tags, labels)"
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: "${{ env.REGISTRY }}/${{ github.repository }}-${{ matrix.name_suffix }}"
    - name: build and push container image
      uses: docker/build-push-action@v6
      with:
        context: "${{ matrix.container_path }}"
        file: "${{ matrix.dockerfile_path }}"
        push: ${{ github.ref_type == 'tag' || (inputs.push != null && inputs.push) }}
        tags: ${{ github.event_name == 'workflow_dispatch' && inputs.tag != '' && format('{0}/{1}-{2}:{3}', env.REGISTRY, github.repository, matrix.name_suffix, inputs.tag) || steps.meta.outputs.tags }}
        labels: "${{ steps.meta.outputs.labels }}"
